### ISSUE TITLE
Duplicate Database entry error discovered in peewee after card images were entered

### ISSUE THREAD

**Issue by Bhargav-Dave** [tattle-made/viral-spiral-backend#96]
Currently rooms are not being created at times due to the following duplicate entry error popping up. The slacktrace of the error is given below. 

```
emitting event "error" to a5ai4ePXrjgxR5IdAAAL [/]
(1062, "Duplicate entry 'cats-3e107eb354b44cbdac317322aac81d95' for key 'affinitytopic.affinitytopic_name_game_id'")
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1062, "Duplicate entry 'cats-3e107eb354b44cbdac317322aac81d95' for key 'affinitytopic.affinitytopic_name_game_id'")  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/flask_socketio/__init__.py", line 828, in _handle_event       
    ret = handler(*args)
  File "/app/main_loop/websocket.py", line 349, in create_game
    for progress in WebsocketGameRunner.create(
  File "/app/main_loop/websocket.py", line 239, in create
    for progress in Game.new(**game_kwargs):
  File "/app/models/base.py", line 226, in new
    topic_objs.append(AffinityTopic.create(name=topic_name, game=game))
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/peewee.py", line 6532, in create
    inst.save(force_insert=True)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/peewee.py", line 6742, in save
    pk = self.insert(**field_dict).execute()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/peewee.py", line 1962, in inner
    return method(self, database, *args, **kwargs)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/peewee.py", line 2033, in execute
    return self._execute(database)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/peewee.py", line 2838, in _execute
    return super(Insert, self)._execute(database)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/peewee.py", line 2551, in _execute
    cursor = database.execute(self)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/peewee.py", line 3250, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/peewee.py", line 3244, in execute_sql
    self.commit()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/peewee.py", line 3010, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
peewee.IntegrityError: (1062, "Duplicate entry 'cats-3e107eb354b44cbdac317322aac81d95' for key 'affinitytopic.affinitytopic_name_game_id'")  
```

**Comment by Bhargav-Dave** [comment]
Moving this issue to done since this one does not seem to occur currently after I updated my local database, has not occured in a while, will reopen the issue if needed and investigate further
